import type { Metadata } from "next";
import {Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "../../components/Header/Header";



const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <div className="bg-[url(/Images/Cover.jpeg)]  w-full h-screen bg-cover  bg-no-repeat">
      <Header/>
      
      <body
        className={roboto_mono.className}
        >
        {children}
      </body>
      </div>
  
    </html>
  );
}
