import type { Metadata } from "next";
import {Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "../../components/Header/Header";
import Footer from "../../components/Footer/Footer";
import LayoutWrapper from "../../Wrapper/LayoutWrapper";



const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={roboto_mono.className}
      >
      <LayoutWrapper>
      <Header/>
        {children}
      <Footer/>
       </LayoutWrapper>
      </body>
    </html>
  );
}
